name: bikersworld
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  bubble_bottom_bar: ^1.2.0
  custom_dropdown: ^0.0.2
  percent_indicator: ^2.1.8
  flutter_rating_bar: ^3.2.0+1
  lite_rolling_switch: ^0.1.1
  line_icons: ^0.2.0
  multilevel_drawer: ^1.0.3
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2
  firebase_core: ^0.7.0
  flutter_vector_icons: ^0.3.0
  contained_tab_bar_view: ^0.7.1
  firebase_auth: ^0.20.0+1
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  fluttertoast: ^7.1.6
  email_validator: ^1.0.5
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  country_state_city_picker: ^1.2.6
  persistent_bottom_nav_bar: ^3.2.0
  flutter_datetime_picker: ^1.5.0
  day_picker: ^1.0.1
  image_picker: ^0.6.7+22
  rflutter_alert: ^1.1.0
  dropdownfield: ^1.0.3
  searchable_dropdown: ^1.1.3
  scrollable_bottom_sheet: ^0.2.1
  provider: ^4.3.1
  dropdown_search: ^0.4.0
  flutter_staggered_grid_view: ^0.3.4
  vertical_tabs: ^0.2.0
  custom_radio: ^0.1.2
  circular_profile_avatar: ^1.0.8
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Ads/
    - assets/autoPartStore/


  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500

