name: bikersworld
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  bubble_bottom_bar: ^1.2.0
  custom_dropdown: ^0.0.2
  percent_indicator: ^2.1.8
  flutter_rating_bar: ^3.2.0+1
  lite_rolling_switch: ^0.1.1
  line_icons: ^0.2.0
  multilevel_drawer: ^1.0.3
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.2
  firebase_core: ^0.7.0
  flutter_vector_icons: ^0.3.0
  contained_tab_bar_view: ^0.7.1
  firebase_auth: ^0.20.0+1
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  fluttertoast: ^7.1.6
  email_validator: ^1.0.5
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  country_state_city_picker: ^1.2.6
  persistent_bottom_nav_bar: ^3.2.0
  flutter_datetime_picker: ^1.5.0
  day_picker: ^1.0.1
  image_picker: ^0.6.7+22
  rflutter_alert: ^1.1.0
  dropdownfield: ^1.0.3
  searchable_dropdown: ^1.1.3
  provider: ^4.3.1
  dropdown_search: ^0.4.0
  vertical_tabs: ^0.2.0
  custom_radio: ^0.1.2
  circular_profile_avatar: ^1.0.8
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  simple_animations: ^2.5.0
  page_transition: ^1.1.7+6
  image_form_field: ^0.1.0
  flat_icons_flutter: ^1.0.1
  random_color: ^1.0.5
  timelines: ^0.0.1
  timeline_tile: ^0.1.0
  steps: ^1.0.1
  multi_image_picker: ^4.7.15
  flutter_absolute_path: ^1.0.6
  url_launcher: ^5.4.5
  image_slider: ^1.0.2
  shimmer: ^1.1.2
  flutter_custom_clippers: ^1.1.2
  google_nav_bar: ^4.0.2
  paginate_firestore: ^0.3.0
  dotted_border: ^1.0.7
  intl: ^0.16.1
  flutter_native_image: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Ads/
    - assets/autoPartStore/


  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500

